//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.stockService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfS_stocks", Namespace="http://localhost:50496/StockExchange.asmx", ItemName="s_stocks")]
    [System.SerializableAttribute()]
    public class ArrayOfS_stocks : System.Collections.Generic.List<web.stockService.s_stocks> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="s_stocks", Namespace="http://localhost:50496/StockExchange.asmx")]
    [System.SerializableAttribute()]
    public partial class s_stocks : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private System.Nullable<int> quantityField;
        
        private System.Nullable<int> priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_guidField;
        
        private bool is_activeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string user_guid {
            get {
                return this.user_guidField;
            }
            set {
                if ((object.ReferenceEquals(this.user_guidField, value) != true)) {
                    this.user_guidField = value;
                    this.RaisePropertyChanged("user_guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool is_active {
            get {
                return this.is_activeField;
            }
            set {
                if ((this.is_activeField.Equals(value) != true)) {
                    this.is_activeField = value;
                    this.RaisePropertyChanged("is_active");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:50496/StockExchange.asmx", ConfigurationName="stockService.StockExchangeSoap")]
    public interface StockExchangeSoap {
        
        // CODEGEN: Generating message contract since element name userGuid from namespace http://localhost:50496/StockExchange.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:50496/StockExchange.asmx/GetStocks", ReplyAction="*")]
        web.stockService.GetStocksResponse GetStocks(web.stockService.GetStocksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:50496/StockExchange.asmx/GetStocks", ReplyAction="*")]
        System.Threading.Tasks.Task<web.stockService.GetStocksResponse> GetStocksAsync(web.stockService.GetStocksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStocksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStocks", Namespace="http://localhost:50496/StockExchange.asmx", Order=0)]
        public web.stockService.GetStocksRequestBody Body;
        
        public GetStocksRequest() {
        }
        
        public GetStocksRequest(web.stockService.GetStocksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:50496/StockExchange.asmx")]
    public partial class GetStocksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userGuid;
        
        public GetStocksRequestBody() {
        }
        
        public GetStocksRequestBody(string userGuid) {
            this.userGuid = userGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStocksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStocksResponse", Namespace="http://localhost:50496/StockExchange.asmx", Order=0)]
        public web.stockService.GetStocksResponseBody Body;
        
        public GetStocksResponse() {
        }
        
        public GetStocksResponse(web.stockService.GetStocksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:50496/StockExchange.asmx")]
    public partial class GetStocksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web.stockService.ArrayOfS_stocks GetStocksResult;
        
        public GetStocksResponseBody() {
        }
        
        public GetStocksResponseBody(web.stockService.ArrayOfS_stocks GetStocksResult) {
            this.GetStocksResult = GetStocksResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockExchangeSoapChannel : web.stockService.StockExchangeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockExchangeSoapClient : System.ServiceModel.ClientBase<web.stockService.StockExchangeSoap>, web.stockService.StockExchangeSoap {
        
        public StockExchangeSoapClient() {
        }
        
        public StockExchangeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockExchangeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockExchangeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockExchangeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.stockService.GetStocksResponse web.stockService.StockExchangeSoap.GetStocks(web.stockService.GetStocksRequest request) {
            return base.Channel.GetStocks(request);
        }
        
        public web.stockService.ArrayOfS_stocks GetStocks(string userGuid) {
            web.stockService.GetStocksRequest inValue = new web.stockService.GetStocksRequest();
            inValue.Body = new web.stockService.GetStocksRequestBody();
            inValue.Body.userGuid = userGuid;
            web.stockService.GetStocksResponse retVal = ((web.stockService.StockExchangeSoap)(this)).GetStocks(inValue);
            return retVal.Body.GetStocksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.stockService.GetStocksResponse> web.stockService.StockExchangeSoap.GetStocksAsync(web.stockService.GetStocksRequest request) {
            return base.Channel.GetStocksAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.stockService.GetStocksResponse> GetStocksAsync(string userGuid) {
            web.stockService.GetStocksRequest inValue = new web.stockService.GetStocksRequest();
            inValue.Body = new web.stockService.GetStocksRequestBody();
            inValue.Body.userGuid = userGuid;
            return ((web.stockService.StockExchangeSoap)(this)).GetStocksAsync(inValue);
        }
    }
}
