//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class co_stocksEntities : DbContext
    {
        public co_stocksEntities()
            : base("name=co_stocksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<s_currencies> s_currencies { get; set; }
        public DbSet<s_users> s_users { get; set; }
        public DbSet<s_stocks> s_stocks { get; set; }
        public DbSet<stock_settings> stock_settings { get; set; }
    }
}
