//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;

    public partial class s_stocks
    {
        public int Id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> price { get; set; }
        public string user_guid { get; set; }
        public bool is_active { get; set; }
    }
}
